/*create user english_web_test identified by 123
grant create session to english_web_test
grant create table to english_web_test
grant create PROCEDURE to english_web_test
alter user english_web_test quota 100M on users
GRANT RESOURCE TO english_web_test;
GRANT CREATE VIEW TO english_web_test;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO english_web_test;*/


--Xoa bang
DROP TABLE Notifications CASCADE CONSTRAINTS;
DROP TABLE Progress CASCADE CONSTRAINTS;
DROP TABLE Payments CASCADE CONSTRAINTS;
DROP TABLE Grades CASCADE CONSTRAINTS;
DROP TABLE Feedback CASCADE CONSTRAINTS;
DROP TABLE DK_COURSES CASCADE CONSTRAINTS;
DROP TABLE Exercises CASCADE CONSTRAINTS;
DROP TABLE Contents CASCADE CONSTRAINTS;
DROP TABLE Lessons CASCADE CONSTRAINTS;
DROP TABLE Modules CASCADE CONSTRAINTS;
DROP TABLE Courses CASCADE CONSTRAINTS;
DROP TABLE Languages CASCADE CONSTRAINTS;
DROP TABLE User_roles CASCADE CONSTRAINTS;
DROP TABLE Users CASCADE CONSTRAINTS;
DROP TABLE Roles CASCADE CONSTRAINTS;
DROP FUNCTION hash_password;
/* XÓA HÀM HASH CŨ (NẾU TỒN TẠI) ĐỂ TẠO LẠI */
BEGIN
   EXECUTE IMMEDIATE 'DROP FUNCTION hash_password';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -4043 THEN
         RAISE;
      END IF;
END;
COMMIT;
-- ==============================================================================
--                              TAO BANG
-- ============================================================================
-- 1. Roles
CREATE TABLE Roles (
    role_id  NUMBER PRIMARY KEY,
    role_name VARCHAR2(50) NOT NULL UNIQUE
);

-- 2. Users
CREATE TABLE Users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name NVARCHAR2(50) UNIQUE NOT NULL,
    password_hash VARCHAR2(256) NULL, 
    email VARCHAR2(100) NOT NULL UNIQUE,
    full_name VARCHAR2(100),
    create_at DATE DEFAULT SYSDATE
);

/* THÊM LẠI HÀM HASH_PASSWORD */
CREATE OR REPLACE FUNCTION hash_password(p_password VARCHAR2)
RETURN VARCHAR2
IS
    v_hash RAW(32);
BEGIN
    v_hash := DBMS_CRYPTO.HASH(UTL_RAW.CAST_TO_RAW(p_password), DBMS_CRYPTO.HASH_SH256);
    RETURN RAWTOHEX(v_hash); -- trả về dạng HEX
END;
/
-- 3. User_roles
CREATE TABLE User_roles (
    user_role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,
    CONSTRAINT FK_USER_ID FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
    CONSTRAINT FK_ROLE_ID FOREIGN KEY (role_id) REFERENCES Roles(role_id) ON DELETE CASCADE
);

-- 4. Languages
CREATE TABLE Languages (
    language_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

-- 5. Courses
CREATE TABLE Courses (
    course_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title NVARCHAR2(200) NOT NULL,
    description CLOB,
    teacher_id NUMBER NOT NULL,
    language_id NUMBER NOT NULL,
    fee NUMBER(10,2) DEFAULT 0,
    create_at DATE DEFAULT SYSDATE,
    CONSTRAINT FK_TEACHER FOREIGN KEY (teacher_id) REFERENCES Users(user_id),
    CONSTRAINT FK_LANG FOREIGN KEY (language_id) REFERENCES Languages(language_id)
);

-- 6. Modules
CREATE TABLE Modules (
    module_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id NUMBER NOT NULL,
    title NVARCHAR2(200) NOT NULL,
    order_num NUMBER,
    CONSTRAINT FK_MODULE_COURSE FOREIGN KEY (course_id) REFERENCES Courses(course_id) ON DELETE CASCADE
);


-- 7. Lessons
CREATE TABLE Lessons (
    lesson_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id NUMBER NOT NULL,
    course_id NUMBER NOT NULL,
    order_num NUMBER,
    title NVARCHAR2(200) NOT NULL,
    content_type NVARCHAR2(50),
    CONSTRAINT FK_LESSON_MODULE FOREIGN KEY (module_id) REFERENCES Modules(module_id) ON DELETE CASCADE,
    CONSTRAINT FK_LESSON_COURSE FOREIGN KEY (course_id) REFERENCES Courses(course_id) ON DELETE CASCADE
);

-- 8. Contents
CREATE TABLE Contents (
    content_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title NVARCHAR2(200),
    type VARCHAR2(50) NOT NULL,
    file_path NVARCHAR2(500),
    lesson_id NUMBER NOT NULL,
    course_id NUMBER NOT NULL,
    FOREIGN KEY (lesson_id) REFERENCES Lessons(lesson_id) ON DELETE CASCADE
);

-- 9. Exercises
CREATE TABLE Exercises (
    exercise_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title NVARCHAR2(200) NOT NULL,
    type VARCHAR2(50) NOT NULL,
    content CLOB,
    lesson_id NUMBER NOT NULL,
    FOREIGN KEY (lesson_id) REFERENCES Lessons(lesson_id) ON DELETE CASCADE
);

-- Thêm cột mật mã vào bảng Exercises
ALTER TABLE Exercises ADD access_code VARCHAR2(100);
COMMIT;

-- 10. Enrollments (DK_COURSES)
CREATE TABLE DK_COURSES (
    dk_courses_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER NOT NULL,
    course_id NUMBER NOT NULL,
    enroll_date DATE DEFAULT SYSDATE,
    status VARCHAR2(20) DEFAULT 'active',
    FOREIGN KEY (student_id) REFERENCES Users(user_id),
    FOREIGN KEY (course_id) REFERENCES Courses(course_id),
    UNIQUE (student_id, course_id)
);

-- 11. Feedback (tạo trước để Grades dùng)
CREATE TABLE Feedback (
    feedback_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id NUMBER NOT NULL,
    student_id NUMBER NOT NULL,
    exercise_id NUMBER,
    content CLOB NOT NULL,
    created_at DATE DEFAULT SYSDATE,
    FOREIGN KEY (teacher_id) REFERENCES Users(user_id),
    FOREIGN KEY (student_id) REFERENCES Users(user_id),
    FOREIGN KEY (exercise_id) REFERENCES Exercises(exercise_id)
);

-- 12. Grades
CREATE TABLE Grades (
    dk_courses_id NUMBER NOT NULL,
    exercise_id NUMBER NOT NULL,
    score NUMBER(5,2) CHECK (score BETWEEN 0 AND 100),
    date_graded DATE DEFAULT SYSDATE,
    feedback_id NUMBER,
    PRIMARY KEY (dk_courses_id, exercise_id),
    FOREIGN KEY (dk_courses_id) REFERENCES DK_COURSES(dk_courses_id) ON DELETE CASCADE,
    FOREIGN KEY (exercise_id) REFERENCES Exercises(exercise_id),
    FOREIGN KEY (feedback_id) REFERENCES Feedback(feedback_id)
);

-- 13. Payments
CREATE TABLE Payments (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER NOT NULL,
    course_id NUMBER NOT NULL,
    amount NUMBER(10,2) NOT NULL,
    payment_date DATE DEFAULT SYSDATE,
    status VARCHAR2(20) DEFAULT 'pending',
    FOREIGN KEY (student_id) REFERENCES Users(user_id),
    FOREIGN KEY (course_id) REFERENCES Courses(course_id)
);

-- 14. Notifications
CREATE TABLE Notifications (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    message CLOB NOT NULL,
    type VARCHAR2(50),
    sent_date DATE DEFAULT SYSDATE,
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);
-- 15. Progress
CREATE TABLE Progress (
    dk_courses_id NUMBER NOT NULL,
    lesson_id NUMBER NOT NULL,
    progress NUMBER(5,2) CHECK (progress BETWEEN 0 AND 100),
    last_updated DATE DEFAULT SYSDATE,
    PRIMARY KEY (dk_courses_id, lesson_id),
    FOREIGN KEY (dk_courses_id) REFERENCES DK_COURSES(dk_courses_id) ON DELETE CASCADE,
    FOREIGN KEY (lesson_id) REFERENCES Lessons(lesson_id)
);


--=============================================================================================
-- Trigger: Đảm bảo chỉ teacher được tạo course
CREATE OR REPLACE TRIGGER trg_check_quyen_role
BEFORE INSERT OR UPDATE ON Courses
FOR EACH ROW
DECLARE 
    v_role_count NUMBER;
BEGIN 
    SELECT COUNT(*)
    INTO v_role_count
    FROM User_roles ur
    JOIN Roles r ON ur.role_id = r.role_id
    WHERE ur.user_id = :NEW.teacher_id 
      AND r.role_name = 'teacher';
    
    IF v_role_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Chi co "teacher" moi duoc tao khoa hoc');
    END IF;
END;
/

-- Trigger: Đảm bảo chỉ student được enroll
CREATE OR REPLACE TRIGGER trg_check_student_role
BEFORE INSERT OR UPDATE ON DK_COURSES
FOR EACH ROW
DECLARE
    v_role_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_role_count
    FROM User_roles ur
    JOIN Roles r ON ur.role_id = r.role_id
    WHERE ur.user_id = :NEW.student_id 
      AND r.role_name = 'student';
    
    IF v_role_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Chi co "student" moi duoc dang ky');
    END IF;
END;
/

-- Trigger: Đảm bảo chỉ teacher được viết feedback
CREATE OR REPLACE TRIGGER trg_check_feedback_teacher
BEFORE INSERT OR UPDATE ON Feedback
FOR EACH ROW
DECLARE
    v_role_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_role_count
    FROM User_roles ur
    JOIN Roles r ON ur.role_id = r.role_id
    WHERE ur.user_id = :NEW.teacher_id 
      AND r.role_name = 'teacher';
    
    IF v_role_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'Chi co "teacher" moi duoc viet feedback');
    END IF;
END;
/



--==============================================================================
--====================== THEM DU LIEU==========================================

--1.Roles
INSERT INTO Roles (role_id, role_name) VALUES (1, 'admin');
INSERT INTO Roles (role_id, role_name) VALUES (2, 'teacher');
INSERT INTO Roles (role_id, role_name) VALUES (3, 'student');


--2.User
/* SỬA LẠI: INSERT vào CẢ HAI cột password và password_hash */
INSERT INTO Users (user_id, user_name,email, full_name, password_hash) 
VALUES (1, 'admin1', 'admin1@gmail.com', 'Truong Tan Hoai', HASH_PASSWORD('123') );

INSERT INTO Users (user_id, user_name, email, full_name, password_hash) 
VALUES (2, 'teacher1', 'teacher1@gmail.com', 'Mr. Smith', HASH_PASSWORD('123') );

INSERT INTO Users (user_id, user_name, email, full_name, password_hash) 
VALUES (3, 'student1', 'student1@gmail.com', 'Nguyen Van A', HASH_PASSWORD('1234') );

INSERT INTO Users (user_id, user_name, email, full_name, password_hash) 
VALUES (4, 'student2', 'student2@gmail.com', 'Le Thi B', HASH_PASSWORD('12345') );

INSERT INTO Users (user_id, user_name, email, full_name, password_hash)
values (5, 'teacher2', 'teacher2@gmail.com','Ms.Maria',HASH_PASSWORD('12345'));

--3.User_roles
--ID : 1 ADMIN
INSERT INTO User_roles (user_id, role_id) VALUES (1, 1);

-- ID 2 : TEACHER
INSERT INTO User_roles (user_id, role_id) VALUES (2, 2); 
INSERT INTO User_roles (user_id, role_id) VALUES (5, 2);

-- ID 3 : STUDENT
INSERT INTO User_roles (user_id, role_id) VALUES (3, 3); 
INSERT INTO User_roles (user_id, role_id) VALUES (4, 3);


--4.Languages
INSERT INTO Languages (language_id, name) VALUES (1, 'English');
INSERT INTO Languages (language_id, name) VALUES (2, 'French');



--5. Courses
INSERT INTO Courses (course_id, title, description, teacher_id, language_id, fee) 
VALUES (1, 'English Speaking Basics', 'Course for beginners', 2, 1, 100.00);

INSERT INTO Courses (course_id, title, description, teacher_id, language_id, fee) 
VALUES (2, 'French for Travelers', 'Learn French phrases for travel', 2, 2, 150.00);

--6. Modules
INSERT INTO Modules (title, order_num, course_id) 
VALUES ('Introduction to English', 1, 1);

INSERT INTO Modules (title, order_num, course_id) 
VALUES ('Basic Conversations', 2, 1);

INSERT INTO Modules (title, order_num, course_id) 
VALUES ('French Basics', 1, 2);

--7. Lessons
INSERT INTO Lessons (course_id, module_id, order_num, title, content_type)
VALUES (1, 1, 1, 'Alphabet and Pronunciation', 'video');

INSERT INTO Lessons (course_id, module_id, order_num, title, content_type)
VALUES (1, 2, 1, 'Greetings and Introductions', 'text');

INSERT INTO Lessons (course_id, module_id, order_num, title, content_type)
VALUES (2, 1, 1, 'Basic French Greetings', 'video');

--8. Contents
INSERT INTO Contents (content_id, title, type, file_path, course_id, lesson_id)
VALUES (1, 'Alphabet Video', 'video', '/videos/eng_alphabet.mp4', 1, 1);

INSERT INTO Contents (content_id, title, type, file_path, course_id, lesson_id)
VALUES (2, 'Greetings PDF', 'document', '/docs/eng_greetings.pdf', 1, 2);

--9. Exercises
INSERT INTO Exercises (exercise_id, title, type, content, lesson_id)
VALUES (1, 'Alphabet Quiz', 'quiz', 'Choose correct pronunciation',1);

INSERT INTO Exercises (exercise_id, title, type, content, lesson_id)
VALUES (2, 'Greetings Practice', 'assignment', 'Write 5 greetings',2);

--10. Đk_courses
INSERT INTO DK_COURSES (dk_courses_id, student_id, course_id, status) 
VALUES (1, 3, 1, 'active');

INSERT INTO DK_COURSES (dk_courses_id, student_id, course_id, status) 
VALUES (2, 4, 1, 'active');

--11. Grades
INSERT INTO Grades (dk_courses_id, exercise_id, score) 
VALUES (1, 1, 85.5);

INSERT INTO Grades (dk_courses_id, exercise_id, score) 
VALUES (2, 2, 90.0);


--12. Payments
INSERT INTO Payments (payment_id, student_id, course_id, amount, status) 
VALUES (1, 3, 1, 100.00, 'paid');

INSERT INTO Payments (payment_id, student_id, course_id, amount, status) 
VALUES (2, 4, 1, 100.00, 'pending');

--13. Notifications
INSERT INTO Notifications (notification_id, user_id, message, type) 
VALUES (1, 3, 'Welcome to English Speaking Basics!', 'info');

INSERT INTO Notifications (notification_id, user_id, message, type) 
VALUES (2, 4, 'Your payment is pending.', 'warning');

--14. Feedback
INSERT INTO Feedback (feedback_id, teacher_id, student_id, exercise_id, content) 
VALUES (1, 2, 3, 1, 'Good pronunciation, but improve on vowels.');

INSERT INTO Feedback (feedback_id, teacher_id, student_id, exercise_id, content) 
VALUES (2, 2, 4, 2, 'Great job on greetings!');

--15.Progress
INSERT INTO Progress (dk_courses_id, lesson_id, progress) 
VALUES (1, 1, 50.0);

INSERT INTO Progress (dk_courses_id, lesson_id, progress) 
VALUES (2, 2, 30.0);

-- Sửa lỗi cho bảng Courses (Bắt đầu đếm từ 10 trở đi)
ALTER TABLE Courses MODIFY (course_id GENERATED AS IDENTITY (START WITH 10));

-- Tiện thể sửa luôn cho các bảng khác bạn cũng nhập thủ công ID để tránh lỗi sau này:
ALTER TABLE Users MODIFY (user_id GENERATED AS IDENTITY (START WITH 10));
ALTER TABLE Exercises MODIFY (exercise_id GENERATED AS IDENTITY (START WITH 10));
ALTER TABLE Contents MODIFY (content_id GENERATED AS IDENTITY (START WITH 10));
ALTER TABLE DK_COURSES MODIFY (dk_courses_id GENERATED AS IDENTITY (START WITH 10));
ALTER TABLE Payments MODIFY (payment_id GENERATED AS IDENTITY (START WITH 10));
ALTER TABLE Notifications MODIFY (notification_id GENERATED AS IDENTITY (START WITH 10));
ALTER TABLE Feedback MODIFY (feedback_id GENERATED AS IDENTITY (START WITH 10));

-- Tự động tìm khóa học mới nhất vừa tạo
DECLARE
    v_max_course_id NUMBER;
    v_max_module_id NUMBER;
BEGIN
    -- 1. Lấy ID khóa học mới nhất
    SELECT MAX(course_id) INTO v_max_course_id FROM Courses;

    -- 2. Tạo 1 Module cho khóa học đó
    INSERT INTO Modules (title, order_num, course_id) 
    VALUES ('Chương 1: Khởi động', 1, v_max_course_id)
    RETURNING module_id INTO v_max_module_id;

    -- 3. Tạo 1 Bài học cho Module đó (NÚT TẠO QUIZ SẼ HIỆN Ở ĐÂY)
    INSERT INTO Lessons (module_id, course_id, order_num, title, content_type)
    VALUES (v_max_module_id, v_max_course_id, 1, 'Bài 1: Giới thiệu tổng quan', 'video');

    COMMIT;
END;

SELECT exercise_id, title, content 
FROM Exercises 
ORDER BY exercise_id DESC;

COMMIT;
